version: "3"

volumes:
  rabbitmq-01-data:
    driver: local

services:
  rabbitmq:
    image: rabbitmq:3.8-management-alpine
    hostname: rabbitmq-01
    ports:
      - ${RABBITMQ_PORT}:5672
      - ${RABBITMQ_ADMIN_PORT}:15672
    volumes:
      - "rabbitmq-01-data:/var/lib/rabbitmq"
    environment:
      RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
      RABBITMQ_DEFAULT_VHOST: ${RABBITMQ_DEFAULT_VHOST}

  # gateway:
  #   ports:
  #     - ${GATEWAY_PORT}:${GATEWAY_PORT}
  #   depends_on:
  #     - rabbitmq

  # ms_catalog:
  #   ports:
  #     - ${MS_CATALOG_PORT}:${MS_CATALOG_PORT}
  #   depends_on:
  #     - rabbitmq

  # ms_basket:
  #   ports:
  #     - ${MS_BASKET_PORT}:${MS_BASKET_PORT}
  #   depends_on:
  #     - rabbitmq

  # ms_log:
  #   ports:
  #     - ${MS_LOG_PORT}:${MS_LOG_PORT}
  #   depends_on:
  #     - rabbitmq
