ARG NODE_VER=12

################################################################################
## STAGE 1 - BUILDER-DEV IMAGE #################################################

# Do npm install & build with full image
FROM mhart/alpine-node:${NODE_VER} as builder
LABEL maintainer="Emre CAMDERE <cemre79@gmail.com>"
ARG ENV
ARG VER
ARG NAME
ARG RABBITMQ_USERNAME
ARG RABBITMQ_PASSWORD
ARG RABBITMQ_HOST
ARG RABBITMQ_PORT

ENV NODE_ENV=production 

RUN printf "\n\nBuilding ${NAME} builder version: ${VER}\n\n"

RUN mkdir /build
WORKDIR /build
COPY package.json package-lock.json .env.dist ./
COPY src ./src
RUN  chmod u+x ./src/wait-dependencies.sh
RUN eval "echo \"$(cat .env.dist)\"" > .env && \
  npm set progress=false && \
  npm install --production


# ################################################################################
# ## STAGE 2 - PROD APP ##########################################################

# And then copy over node_modules, etc from that stage to the smaller base image
FROM mhart/alpine-node:slim-${NODE_VER}
LABEL maintainer="Emre CAMDERE <cemre79@gmail.com>"
LABEL description="FM Logger"

ARG TZ
ARG VER
ARG NAME
ARG LISTEN

ENV TZ ${TZ}
ENV LISTEN ${LISTEN}
ENV NODE_ENV production
ENV DOCKER true

RUN printf "\n\nBuilding ${NAME} prod version: ${VER}\n\n"

# update  packages
RUN apk update \
  && rm -rf /var/cache/apk/* \
  && rm -rf /var/lib/apt/lists/*

RUN mkdir /app 
WORKDIR /app
COPY --from=builder /build .

# Start the app
CMD ["./src/wait-dependencies.sh", "node", "./src/app.js"]
# CMD ["./src/wait-dependencies.sh", "./node_modules/.bin/forever", "./src/app.js"]
