ARG NODE_VER=12

################################################################################
## STAGE 1 - BUILDER-DEV IMAGE #################################################

# Do npm install & build with full image
FROM mhart/alpine-node:${NODE_VER} as builder
LABEL maintainer="Emre CAMDERE <cemre79@gmail.com>"
ARG ENV
ARG VER
ARG NAME
ARG RABBITMQ_USERNAME
ARG RABBITMQ_PASSWORD
ARG RABBITMQ_HOST
ARG RABBITMQ_PORT

ENV NODE_ENV=production 
ENV VER=${VER}
ENV NAME=${NAME}

RUN echo "Building ${NAME} builder version: ${VER}"
RUN mkdir /build
WORKDIR /build
COPY package.json package-lock.json .env.dist ./
COPY src ./src
RUN eval "echo \"$(cat .env.dist)\"" > .env && \
    npm set progress=false && \
    npm install --production


# ################################################################################
# ## STAGE 2 - PROD APP ##########################################################

# And then copy over node_modules, etc from that stage to the smaller base image
FROM mhart/alpine-node:slim-${NODE_VER}
LABEL maintainer="Emre CAMDERE <cemre79@gmail.com>"
LABEL description="FM Product service"

# update  packages
RUN apk update \
    && rm -rf /var/cache/apk/* \
    && rm -rf /var/lib/apt/lists/*

ARG TZ
ARG VER
ARG NAME
ARG LISTEN

ENV TZ ${TZ}
ENV NODE_ENV production
ENV DOCKER true
ENV VER ${VER}
ENV NAME ${NAME}

RUN echo "Building ${NAME} prod version: ${VER}"
RUN mkdir /app 
WORKDIR /app
COPY --from=builder /build .

# Start the app
CMD ["node", "./src/app.js"]
# CMD ["./node_modules/.bin/forever", "./src/app.js"]
